# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 16:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cost_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account_transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_transaction_title', models.CharField(max_length=30)),
                ('account_transaction_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'all transaction',
            },
        ),
        migrations.CreateModel(
            name='Bank_Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_account_title', models.CharField(max_length=30)),
                ('bank_account_balance', models.IntegerField()),
            ],
            options={
                'db_table': 'bank account',
            },
        ),
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.AddField(
            model_name='account_transaction',
            name='bank_to_transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cost_manager.Bank_Account'),
        ),
    ]
