# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 17:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cost_manager', '0002_auto_20171202_1954'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account_Journal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_jornal_amount', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'bank account journal',
            },
        ),
        migrations.RemoveField(
            model_name='account_transaction',
            name='bank_to_transaction',
        ),
        migrations.AddField(
            model_name='account_transaction',
            name='account_transaction_expenditure_name',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Bank_Account',
        ),
        migrations.AddField(
            model_name='account_journal',
            name='bank_account_transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cost_manager.Account_transaction'),
        ),
    ]
