# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cost_manager', '0004_auto_20171202_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account_journal',
            name='account_jornal_status',
            field=models.CharField(choices=[('+', 'Приход'), ('-', 'Расход')], max_length=10),
        ),
        migrations.AlterField(
            model_name='account_transaction',
            name='account_transaction_currency',
            field=models.CharField(choices=[('USD', 'dollars'), ('EUR', 'euro'), ('RUR', 'rubles')], max_length=10),
        ),
    ]
