# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cost_manager', '0005_auto_20171202_2045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account_transaction',
            name='account_transaction_title',
        ),
        migrations.AddField(
            model_name='account_transaction',
            name='bank_account_title',
            field=models.CharField(choices=[('1', 'Главный'), ('2', 'Сберегательный'), ('3', 'Валютный')], default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account_transaction',
            name='account_transaction_expenditure_name',
            field=models.CharField(choices=[('1', 'Мобильный'), ('2', 'ЖКХ'), ('3', 'Перевод'), ('4', 'Продукты'), ('5', 'Транспорт')], max_length=30),
        ),
    ]
