# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 18:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cost_manager', '0006_auto_20171202_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='account_transaction',
            name='blank',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account_transaction',
            name='account_transaction_currency',
            field=models.CharField(choices=[('USD', 'dollars'), ('EUR', 'euro'), ('RUR', 'rubles')], default=models.CharField(max_length=10), max_length=10),
        ),
        migrations.AlterField(
            model_name='account_transaction',
            name='bank_account_title',
            field=models.CharField(choices=[('1', 'Главный'), ('2', 'Сберегательный'), ('3', 'Валютный')], default=models.CharField(max_length=10), max_length=30),
        ),
    ]
