# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 18:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cost_manager', '0007_auto_20171202_2108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account_transaction',
            name='blank',
        ),
        migrations.AlterField(
            model_name='account_transaction',
            name='account_transaction_currency',
            field=models.CharField(blank=True, choices=[('USD', 'dollars'), ('EUR', 'euro'), ('RUR', 'rubles')], max_length=10),
        ),
        migrations.AlterField(
            model_name='account_transaction',
            name='account_transaction_expenditure_name',
            field=models.CharField(help_text='Введите имя расхода, например: ЖКХ \n Продукты \n Перевод на чужую карту', max_length=30),
        ),
        migrations.AlterField(
            model_name='account_transaction',
            name='bank_account_title',
            field=models.CharField(blank=True, help_text='Введите имя счета, например: Основной \n Валютный \n Сберегательный', max_length=30),
        ),
    ]
