# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 19:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cost_manager', '0008_auto_20171202_2137'),
    ]

    operations = [
        migrations.CreateModel(
            name='TEST_CLASS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a', models.TextField()),
                ('b', models.DateTimeField()),
            ],
        ),
    ]
