# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 19:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cost_manager', '0009_test_class'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TEST_CLASS',
        ),
    ]
