# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 20:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cost_manager', '0011_auto_20171202_2336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acceptor',
            name='a',
        ),
        migrations.DeleteModel(
            name='Acceptor',
        ),
        migrations.DeleteModel(
            name='Variations',
        ),
    ]
