# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 21:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cost_manager', '0012_auto_20171202_2358'),
    ]

    operations = [
        migrations.AddField(
            model_name='account_transaction',
            name='account_transaction_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='account_transaction',
            name='account_transaction_comment',
            field=models.CharField(default='comment...', max_length=30),
        ),
    ]
