# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 21:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cost_manager', '0013_auto_20171203_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account_transaction',
            name='account_transaction_currency',
            field=models.CharField(blank=True, choices=[('USD', 'dollars'), ('EUR', 'euro'), ('RUR', 'rubles')], default='rubles', max_length=10),
        ),
    ]
