# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 21:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cost_manager', '0014_auto_20171203_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account_transaction',
            name='account_transaction_expenditure_name',
            field=models.CharField(help_text='Введите статью расходов или источник дохода', max_length=30),
        ),
    ]
