# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 23:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cost_manager', '0016_account_transaction_account_jornal_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account_journal',
            name='bank_account_transaction',
        ),
        migrations.DeleteModel(
            name='Account_Journal',
        ),
    ]
