# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 20:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cost_manager', '0020_remove_account_transaction_bank_account_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank_account',
            name='bank_account_balance',
            field=models.IntegerField(default=0, verbose_name='Account balance:'),
        ),
    ]
