# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-11 00:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cost_manager', '0021_bank_account_bank_account_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank_account',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='account_transaction',
            name='bank_account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cost_manager.Bank_Account'),
        ),
    ]
