# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-11 09:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cost_manager', '0022_auto_20171211_0354'),
    ]

    operations = [
        migrations.AddField(
            model_name='account_transaction',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
