# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-11 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cost_manager', '0027_auto_20171211_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='account_transaction',
            name='account_balance',
            field=models.IntegerField(default=0, verbose_name='Account balance:'),
        ),
        migrations.AddField(
            model_name='account_transaction',
            name='account_title',
            field=models.CharField(blank=True, help_text='Введите имя счета, например: Основной \n Валютный \n Сберегательный', max_length=30, verbose_name='Account Name:'),
        ),
    ]
