# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-11 16:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cost_manager', '0028_auto_20171211_1908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account_transaction',
            name='bank_account',
        ),
    ]
