# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-11 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cost_manager', '0029_remove_account_transaction_bank_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bank_account',
            name='user',
        ),
        migrations.AddField(
            model_name='goals_account',
            name='goals_mood',
            field=models.CharField(choices=[('+', 'Goal Achieved'), ('-', 'In developing')], default='In developing', max_length=10, verbose_name='Currency:'),
        ),
        migrations.AlterField(
            model_name='account_transaction',
            name='account_transaction_currency',
            field=models.CharField(choices=[('USD', 'dollars'), ('EUR', 'euro'), ('RUR', 'rubles')], default='rubles', max_length=10, verbose_name='Currency:'),
        ),
        migrations.DeleteModel(
            name='Bank_Account',
        ),
    ]
