# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-11 20:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cost_manager', '0030_auto_20171211_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account_transaction',
            name='account_jornal_status',
            field=models.CharField(choices=[('+', 'Приход'), ('-', 'Расход')], default='+', max_length=10, verbose_name='Operation status:'),
        ),
        migrations.AlterField(
            model_name='account_transaction',
            name='account_transaction_currency',
            field=models.CharField(choices=[('USD', 'dollars'), ('EUR', 'euro'), ('RUR', 'rubles')], default='RUR', max_length=10, verbose_name='Currency:'),
        ),
    ]
